baseURL = 'https://creations.kgol.xyz'
languageCode = 'en-us'
title = 'Goldsworthy Creations'

theme = "hugo-creations"

[menu]
  [[menu.main]]
    name = "About"
    pre = "circle-question-solid"
    url = "/news/about"
    weight = 1
  [[menu.main]]
    name = "Works"
    pre = "yarn-ball"
    url = "/works/"
    weight = 2
  [[menu.main]]
    name = "Sets"
    pre = "yarn-ball-set"
    url = "/sets/"
    weight = 3
  [[menu.main]]
    name = "News"
    pre = "newspaper-regular"
    url = "/news/"
    weight = 4
  [[menu.main]]
    name = "Shop"
    pre = "shop-solid"
    url = "https://www.ravelry.com/patterns/sources/kieran-goldsworthys-ravelry-store"
    weight = 5
  [[menu.main]]
    name = "Search"
    pre = "search"
    url = "/search"
    weight = 6
